# Site
name: "naznienfevrianne"
title: "naznienfevrianne"
description: "A Writing Dump"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-25YXBMWGGY'
disqus: 'naznienfevrianne-github-io'
mailchimp-list: 'https://gmail.us21.list-manage.com/subscribe/post?u=834f2696005b6f34990222f75&amp;id=15672e41ec&amp;f_id=004fd1e1f0'
include: ["_pages"]
permalink: /:title/
email: nfmalano@gmail.com

# Authors
authors:
  naznien:
    name: Naznien Fevrianne Malano
    display_name: naznienfevrianne
    avatar: 'assets/images/avatar.jpg'
    email: nfmalano@gmail.com
    web: https://github.com/naznienfevrianne
    instagram: https://instagram.com/naznienfevrianne
    linkedin: https://linkedin.com/in/naznien-fevrianne-malano
    description: "Hello. My name is Naznien Fevrianne. I'm an Information Systems undergraduate and currently interested in learning Data Science & Web Development. 
    In this blog, I'll write about my study, the books I read, the movies I watch, and bunch of random things that interesting to write. 
    I'm happy to receive any criticism and suggestions regarding this blog via contact section."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
